version: 2
jobs:
  build-job:
    docker:
      - image: circleci/android:api-26-alpha
    working_directory: ~/repo/sharebottomsheet
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies clean build install
  deploy-job:
    docker:
      - image: my-image
    working_directory: ~/repo/sharebottomsheet
    steps:
      - run:
          name: Clean Build Upload
          command: ./gradlew bintrayUpload

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master