version: 2
jobs:
  build-job:
    docker:
      - image: circleci/android:api-26-alpha
    working_directory: ~/repo/sharebottomsheet
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "sharebottomsheetdialog/build.gradle" }}-{{ checksum "sample/build.gradle" }}
      - run:
          name: Download Dependencies Clean Build
          command: ./gradlew androidDependencies clean build install
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "sharebottomsheetdialog/build.gradle" }}-{{ checksum "sample/build.gradle" }}
  deploy-job:
    docker:
      - image: circleci/android:api-26-alpha
    working_directory: ~/repo/sharebottomsheet
    steps:
      - run:
          name: Upload
          command: ./gradlew bintrayUpload

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master